[project]
name = "rag-pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "aljonnovelo", email = "aljonnovelo30@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "google-genai>=2.24.0",
    "inngest>=0.5.19",
    "llama-index-core>=0.14.24",
    "llama-index-readers-file>=0.7.0",
    "python-dotenv>=1.2.3",
    "qdrant-client>=1.19.1",
    "streamlit>=1.64.0",
    "uvicorn>=0.53.0",
]

[project.scripts]
rag-pdf = "rag_pdf:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
